-- MySQL Script generated by MySQL Workbench
-- 12/21/14 17:01:27
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema a1ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `a1ecommerce` ;
CREATE SCHEMA IF NOT EXISTS `a1ecommerce` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `a1ecommerce` ;

-- -----------------------------------------------------
-- Table `a1ecommerce`.`ProductCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a1ecommerce`.`ProductCategory` ;

CREATE TABLE IF NOT EXISTS `a1ecommerce`.`ProductCategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` TINYTEXT NULL,
  `Description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a1ecommerce`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a1ecommerce`.`Products` ;

CREATE TABLE IF NOT EXISTS `a1ecommerce`.`Products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` TINYTEXT NULL,
  `Quantity` INT NULL,
  `Price` INT NULL,
  `ImagePath` TEXT NULL,
  `ProductCategoryToProducts` INT NOT NULL,
  `Description` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Products_ProductCategory_idx` (`ProductCategoryToProducts` ASC),
  CONSTRAINT `fk_Products_ProductCategory`
    FOREIGN KEY (`ProductCategoryToProducts`)
    REFERENCES `a1ecommerce`.`ProductCategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
